### ISSUE TITLE
how to use that

### ISSUE THREAD

**Issue by alexeyZZZ777** [cheesits456/discord-ssh-bot#2]
i wrote all things to config ,invited the bor but it dont seeem to work

**Comment by cheesits456** [comment]
I'd love to be able to help, but without any information, there's not much I can do. If you can include the following, I can look into what the problem might be:

- The exact contents of your config file (aside from the token, obviously)
- Any error messages you got
- What you’ve tried already, and what happened

**Comment by cheesits456** [comment]
I just pushed a large update that, among other things, includes error catching to properly inform you what went wrong - please try running the updated version and see how that works

**Comment by cheesits456** [comment]
Im gonna close this issue since ive reached out a couple times to try to help you, and have heard no reply in over 2 weeks. if you need anymore help, please don't hesitate to contact me <3
