### ISSUE TITLE
cd

### ISSUE THREAD

**Issue by rowisahub** [cheesits456/discord-ssh-bot#4]
is there any 'cd' like command? because 'cd' doesn't change the directory when i issue the command i

**Comment by cheesits456** [comment]
yeah that's cuz each command executes in its own "sandbox" type thing (idrk the right word for it) and then returns its output. if you wanna execute a command in a different directory, you could do something like `cd /path/to/dir && command`

**Comment by rowisahub** [comment]
oh ok, thanks

**Comment by cheesits456** [comment]
Btw if you (or anyone else reading this) figure out a way to make directory changes persistent, feel free to make a PR - I'd be happy to receive any contributions :)
