### ISSUE TITLE
Can´t read property

### ISSUE THREAD

**Issue by HelixZ** [cheesits456/discord-ssh-bot#9]
Hello I have these error, Any solution?
![image](https://user-images.githubusercontent.com/70325649/100236858-7dc51080-2f2e-11eb-9879-d385fe67b46c.png)

**Comment by cheesits456** [comment]
Did you use a valid user ID in the config file?

**Comment by HelixZ** [comment]
Yes

**Comment by cheesits456** [comment]
Did you set it as a string or an integer? It needs to be a string

**Comment by cheesits456** [comment]
I'll rewrite this soon to give better error messages and make it more clear how to properly configure it

**Comment by HelixZ** [comment]
Okey

**Comment by cheesits456** [comment]
This appears to be the same issue as #7 - as that issue has now been resolved, I'm gonna close this issue <3
